name: CI

on:
  pull_request:

jobs:
    install:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: Cache
          uses: actions/cache@v1.0.3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-client-${{ hashFiles('package-lock.json') }}
        - name: Install
          run: npm ci

    lint:
      needs: install
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: Restore cache
          uses: actions/cache@v1.0.3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-client-${{ hashFiles('package-lock.json') }}
        - name: tsc
          run: npm run lint

    build:
      needs: install
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: Restore cache
          uses: actions/cache@v1.0.3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-client-${{ hashFiles('package-lock.json') }}
        - name: Lint
          run: npm run prepublishOnly
    test:
      needs: install
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: Restore cache
          uses: actions/cache@v1.0.3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-client-${{ hashFiles('package-lock.json') }}
        - name: Lint
          run: npm run test


