name: Slash-commands
on:
  issue_comment:
    types: [created]
jobs:
  slash-command:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: actions/checkout@v2
    - uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{secrets.NPM_TOKEN}}
        issue-type: pull-request
        permission: write
        commands: |
          publish